specVersion: 0.0.5

schema:
  file: ./schema.graphql

dataSources:
  - kind: ethereum
    name: Registry
    network: arbitrum-one
    source:
      address: "0x33Ce0448DEFb2d94Af326C50c39FA20fB53C227a"
      abi: Registry
      startBlock: 79174517
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Registry
        - Aggregator
      abis:
        - name: Registry
          file: ./abis/Registry.json
      eventHandlers:
        - event: MarketAdded(indexed address)
          handler: handleMarketAdded
        - event: MarketRemoved(indexed address)
          handler: handleMarketRemoved
        - event: ThresholdUpdated(uint256)
          handler: handleThresholdUpdated
        - event: VaultAdded(indexed address)
          handler: handleVaultAdded
        - event: VaultRemoved(indexed address)
          handler: handleVaultRemoved
      file: ./src/registry.ts
  
  - kind: ethereum
    name: Vault
    network: arbitrum-one
    source:
      abi: Vault
      startBlock: 79174517
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Registry
        - Deposit
        - Withdraw
      abis:
        - name: Vault
          file: ./abis/Vault.json
      eventHandlers:
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ./src/vault.ts

  - kind: ethereum
    name: Market
    network: arbitrum-one
    source:
      abi: Market
      startBlock: 79174517
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Bet
        - Borrow
        - Repay
        - Registry
        - Aggregator
      abis:
        - name: Market
          file: ./abis/Market.json
        - name: Vault
          file: ./abis/Vault.json
      eventHandlers:
        - event: Placed(uint256,bytes16,bytes16,uint256,uint256,indexed address)
          handler: handlePlaced
        - event: Settled(uint256,uint256,uint8,indexed address)
          handler: handleSettled
        - event: Borrowed(uint256,uint256)
          handler: handleBorrowed
        - event: Repaid(indexed address,uint256)
          handler: handleRepaid
      file: ./src/market.ts
